from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from app.api.deps import get_orchestrator_dep
from app.services.orchestrator import AgentOrchestrator

router = APIRouter()

class OrchestrateRequest(BaseModel):
    agent_id: str = Field(..., example="hermes_coder", description="Identifier of the agent to use")
    query: str = Field(..., example="Write a python script to count files in the local dir", description="The input prompt/command")
    workspace_id: str = Field("default_workspace", description="Active workspace context")

@router.post("/orchestrate")
async def orchestrate_agent(
    request: OrchestrateRequest,
    orchestrator: AgentOrchestrator = Depends(get_orchestrator_dep)
):
    """
    Triggers the ReAct reasoning loop for an agent. Streams the tokens
    generated by the agent back in real time.
    """
    async def token_generator():
        try:
            async for token in orchestrator.orchestrate(
                agent_id=request.agent_id,
                query=request.query,
                workspace_id=request.workspace_id
            ):
                yield token
        except Exception as e:
            yield f"\n[Stream Error: {str(e)}]"

    return StreamingResponse(
        token_generator(),
        media_type="text/event-stream"
    )
